#pragma once

// =============================================================================
// MeshUtils.h -- CPU geometry helpers shared by the assimp importer and the
// built-in primitive generators.
//
// Both producers of mesh data need the same two things assimp's post-process
// chain does not always deliver: tangents when a mesh has UVs but no tangent
// data, and normals when a mesh has neither. Having one implementation is the
// point -- a primitive whose tangents were generated by different code than an
// imported mesh's would light differently under the same normal map.
// =============================================================================

#include "lrpch.h"
#include "Renderer/GpuTypes.h"

#include <vector>

namespace X3
{

	// Per-triangle tangents from UV derivatives, accumulated per vertex, then
	// Gram-Schmidt orthogonalised against the vertex normal.
	//
	// Writes `tangent.xyz` and the handedness sign into `tangent.w`. Where the UV
	// parameterisation is degenerate (zero-area in UV space, or every incident
	// triangle cancelling out) it writes tangent = vec4(0), i.e. w == 0.0, which
	// is THE invalid-tangent sentinel the shader branches on. Do not test for a
	// zero-length tangent vector instead -- that is a float comparison and this
	// is an exact one.
	//
	// PRECONDITION: vertices[i].normalV.xyz is already valid and unit length, and
	// vertices[i].positionU.w / normalV.w already hold the UVs. This function
	// reads both and writes only `tangent`.
	//
	// `tris` indexes into `vertices` GLOBALLY (Gpu::TriRef's contract), and only
	// the range [firstTri, firstTri + triCount) is considered.
	void ComputeTangents(std::vector<Gpu::Vertex>& vertices,
	                     const std::vector<Gpu::TriRef>& tris,
	                     uint32_t firstTri, uint32_t triCount);

	// Face normals accumulated onto their vertices and normalised. The fallback
	// for a mesh that arrives with no normals at all, which should not happen
	// under aiProcessPreset_TargetRealtime_MaxQuality (it includes
	// GenSmoothNormals) but is cheap to be correct about.
	//
	// Writes only `normalV.xyz`; leaves the UV in `normalV.w` untouched.
	void ComputeSmoothNormals(std::vector<Gpu::Vertex>& vertices,
	                          const std::vector<Gpu::TriRef>& tris,
	                          uint32_t firstTri, uint32_t triCount);

}
