#pragma once

#define CODICON_ACCOUNT "\xef\x84\x81"	// U+F101
#define CODICON_ACTIVATE_BREAKPOINTS "\xef\x84\x82"	// U+F102
#define CODICON_ADD "\xef\x84\x83"	// U+F103
#define CODICON_ARCHIVE "\xef\x84\x84"	// U+F104
#define CODICON_ARROW_BOTH "\xef\x84\x85"	// U+F105
#define CODICON_ARROW_CIRCLE_DOWN "\xef\x84\x86"	// U+F106
#define CODICON_ARROW_CIRCLE_LEFT "\xef\x84\x87"	// U+F107
#define CODICON_ARROW_CIRCLE_RIGHT "\xef\x84\x88"	// U+F108
#define CODICON_ARROW_CIRCLE_UP "\xef\x84\x89"	// U+F109
#define CODICON_ARROW_DOWN "\xef\x84\x8a"	// U+F10A
#define CODICON_ARROW_LEFT "\xef\x84\x8b"	// U+F10B
#define CODICON_ARROW_RIGHT "\xef\x84\x8c"	// U+F10C
#define CODICON_ARROW_SMALL_DOWN "\xef\x84\x8d"	// U+F10D
#define CODICON_ARROW_SMALL_LEFT "\xef\x84\x8e"	// U+F10E
#define CODICON_ARROW_SMALL_RIGHT "\xef\x84\x8f"	// U+F10F
#define CODICON_ARROW_SMALL_UP "\xef\x84\x90"	// U+F110
#define CODICON_ARROW_SWAP "\xef\x84\x91"	// U+F111
#define CODICON_ARROW_UP "\xef\x84\x92"	// U+F112
#define CODICON_ATTACH "\xef\x84\x93"	// U+F113
#define CODICON_AZURE_DEVOPS "\xef\x84\x94"	// U+F114
#define CODICON_AZURE "\xef\x84\x95"	// U+F115
#define CODICON_BEAKER_STOP "\xef\x84\x96"	// U+F116
#define CODICON_BEAKER "\xef\x84\x97"	// U+F117
#define CODICON_BELL_DOT "\xef\x84\x98"	// U+F118
#define CODICON_BELL_SLASH_DOT "\xef\x84\x99"	// U+F119
#define CODICON_BELL_SLASH "\xef\x84\x9a"	// U+F11A
#define CODICON_BELL "\xef\x84\x9b"	// U+F11B
#define CODICON_BLANK "\xef\x84\x9c"	// U+F11C
#define CODICON_BOLD "\xef\x84\x9d"	// U+F11D
#define CODICON_BOOK "\xef\x84\x9e"	// U+F11E
#define CODICON_BOOKMARK "\xef\x84\x9f"	// U+F11F
#define CODICON_BRACKET_DOT "\xef\x84\xa0"	// U+F120
#define CODICON_BRACKET_ERROR "\xef\x84\xa1"	// U+F121
#define CODICON_BRIEFCASE "\xef\x84\xa2"	// U+F122
#define CODICON_BROADCAST "\xef\x84\xa3"	// U+F123
#define CODICON_BROWSER "\xef\x84\xa4"	// U+F124
#define CODICON_BUG "\xef\x84\xa5"	// U+F125
#define CODICON_CALENDAR "\xef\x84\xa6"	// U+F126
#define CODICON_CALL_INCOMING "\xef\x84\xa7"	// U+F127
#define CODICON_CALL_OUTGOING "\xef\x84\xa8"	// U+F128
#define CODICON_CASE_SENSITIVE "\xef\x84\xa9"	// U+F129
#define CODICON_CHAT_SPARKLE_ERROR "\xef\x84\xaa"	// U+F12A
#define CODICON_CHAT_SPARKLE_WARNING "\xef\x84\xab"	// U+F12B
#define CODICON_CHAT_SPARKLE "\xef\x84\xac"	// U+F12C
#define CODICON_CHECK_ALL "\xef\x84\xad"	// U+F12D
#define CODICON_CHECK "\xef\x84\xae"	// U+F12E
#define CODICON_CHECKLIST "\xef\x84\xaf"	// U+F12F
#define CODICON_CHEVRON_DOWN "\xef\x84\xb0"	// U+F130
#define CODICON_CHEVRON_LEFT "\xef\x84\xb1"	// U+F131
#define CODICON_CHEVRON_RIGHT "\xef\x84\xb2"	// U+F132
#define CODICON_CHEVRON_UP "\xef\x84\xb3"	// U+F133
#define CODICON_CHIP "\xef\x84\xb4"	// U+F134
#define CODICON_CHROME_CLOSE "\xef\x84\xb5"	// U+F135
#define CODICON_CHROME_MAXIMIZE "\xef\x84\xb6"	// U+F136
#define CODICON_CHROME_MINIMIZE "\xef\x84\xb7"	// U+F137
#define CODICON_CHROME_RESTORE "\xef\x84\xb8"	// U+F138
#define CODICON_CIRCLE_FILLED "\xef\x84\xb9"	// U+F139
#define CODICON_CIRCLE_LARGE_FILLED "\xef\x84\xba"	// U+F13A
#define CODICON_CIRCLE_LARGE "\xef\x84\xbb"	// U+F13B
#define CODICON_CIRCLE_SLASH "\xef\x84\xbc"	// U+F13C
#define CODICON_CIRCLE_SMALL_FILLED "\xef\x84\xbd"	// U+F13D
#define CODICON_CIRCLE_SMALL "\xef\x84\xbe"	// U+F13E
#define CODICON_CIRCLE "\xef\x84\xbf"	// U+F13F
#define CODICON_CIRCUIT_BOARD "\xef\x85\x80"	// U+F140
#define CODICON_CLEAR_ALL "\xef\x85\x81"	// U+F141
#define CODICON_CLIPPY "\xef\x85\x82"	// U+F142
#define CODICON_CLOSE_ALL "\xef\x85\x83"	// U+F143
#define CODICON_CLOSE "\xef\x85\x84"	// U+F144
#define CODICON_CLOUD_DOWNLOAD "\xef\x85\x85"	// U+F145
#define CODICON_CLOUD_UPLOAD "\xef\x85\x86"	// U+F146
#define CODICON_CLOUD "\xef\x85\x87"	// U+F147
#define CODICON_CODE_OSS "\xef\x85\x88"	// U+F148
#define CODICON_CODE_REVIEW "\xef\x85\x89"	// U+F149
#define CODICON_CODE "\xef\x85\x8a"	// U+F14A
#define CODICON_COFFEE "\xef\x85\x8b"	// U+F14B
#define CODICON_COLLAPSE_ALL "\xef\x85\x8c"	// U+F14C
#define CODICON_COLOR_MODE "\xef\x85\x8d"	// U+F14D
#define CODICON_COMBINE "\xef\x85\x8e"	// U+F14E
#define CODICON_COMMENT_DISCUSSION_SPARKLE "\xef\x85\x8f"	// U+F14F
#define CODICON_COMMENT_DISCUSSION "\xef\x85\x90"	// U+F150
#define CODICON_COMMENT_DRAFT "\xef\x85\x91"	// U+F151
#define CODICON_COMMENT_UNRESOLVED "\xef\x85\x92"	// U+F152
#define CODICON_COMMENT "\xef\x85\x93"	// U+F153
#define CODICON_COMPASS_ACTIVE "\xef\x85\x94"	// U+F154
#define CODICON_COMPASS_DOT "\xef\x85\x95"	// U+F155
#define CODICON_COMPASS "\xef\x85\x96"	// U+F156
#define CODICON_COPILOT_BLOCKED "\xef\x85\x97"	// U+F157
#define CODICON_COPILOT_ERROR "\xef\x85\x98"	// U+F158
#define CODICON_COPILOT_IN_PROGRESS "\xef\x85\x99"	// U+F159
#define CODICON_COPILOT_LARGE "\xef\x85\x9a"	// U+F15A
#define CODICON_COPILOT_NOT_CONNECTED "\xef\x85\x9b"	// U+F15B
#define CODICON_COPILOT_SNOOZE "\xef\x85\x9c"	// U+F15C
#define CODICON_COPILOT_SUCCESS "\xef\x85\x9d"	// U+F15D
#define CODICON_COPILOT_UNAVAILABLE "\xef\x85\x9e"	// U+F15E
#define CODICON_COPILOT_WARNING_LARGE "\xef\x85\x9f"	// U+F15F
#define CODICON_COPILOT_WARNING "\xef\x85\xa0"	// U+F160
#define CODICON_COPILOT "\xef\x85\xa1"	// U+F161
#define CODICON_COPY "\xef\x85\xa2"	// U+F162
#define CODICON_COVERAGE "\xef\x85\xa3"	// U+F163
#define CODICON_CREDIT_CARD "\xef\x85\xa4"	// U+F164
#define CODICON_DASH "\xef\x85\xa5"	// U+F165
#define CODICON_DASHBOARD "\xef\x85\xa6"	// U+F166
#define CODICON_DATABASE "\xef\x85\xa7"	// U+F167
#define CODICON_DEBUG_ALL "\xef\x85\xa8"	// U+F168
#define CODICON_DEBUG_ALT_SMALL "\xef\x85\xa9"	// U+F169
#define CODICON_DEBUG_ALT "\xef\x85\xaa"	// U+F16A
#define CODICON_DEBUG_BREAKPOINT_CONDITIONAL_UNVERIFIED "\xef\x85\xab"	// U+F16B
#define CODICON_DEBUG_BREAKPOINT_CONDITIONAL "\xef\x85\xac"	// U+F16C
#define CODICON_DEBUG_BREAKPOINT_DATA_UNVERIFIED "\xef\x85\xad"	// U+F16D
#define CODICON_DEBUG_BREAKPOINT_DATA "\xef\x85\xae"	// U+F16E
#define CODICON_DEBUG_BREAKPOINT_FUNCTION_UNVERIFIED "\xef\x85\xaf"	// U+F16F
#define CODICON_DEBUG_BREAKPOINT_FUNCTION "\xef\x85\xb0"	// U+F170
#define CODICON_DEBUG_BREAKPOINT_LOG_UNVERIFIED "\xef\x85\xb1"	// U+F171
#define CODICON_DEBUG_BREAKPOINT_LOG "\xef\x85\xb2"	// U+F172
#define CODICON_DEBUG_BREAKPOINT_UNSUPPORTED "\xef\x85\xb3"	// U+F173
#define CODICON_DEBUG_CONSOLE "\xef\x85\xb4"	// U+F174
#define CODICON_DEBUG_CONTINUE_SMALL "\xef\x85\xb5"	// U+F175
#define CODICON_DEBUG_CONTINUE "\xef\x85\xb6"	// U+F176
#define CODICON_DEBUG_COVERAGE "\xef\x85\xb7"	// U+F177
#define CODICON_DEBUG_DISCONNECT "\xef\x85\xb8"	// U+F178
#define CODICON_DEBUG_LINE_BY_LINE "\xef\x85\xb9"	// U+F179
#define CODICON_DEBUG_PAUSE "\xef\x85\xba"	// U+F17A
#define CODICON_DEBUG_RERUN "\xef\x85\xbb"	// U+F17B
#define CODICON_DEBUG_RESTART_FRAME "\xef\x85\xbc"	// U+F17C
#define CODICON_DEBUG_RESTART "\xef\x85\xbd"	// U+F17D
#define CODICON_DEBUG_REVERSE_CONTINUE "\xef\x85\xbe"	// U+F17E
#define CODICON_DEBUG_STACKFRAME_ACTIVE "\xef\x85\xbf"	// U+F17F
#define CODICON_DEBUG_STACKFRAME "\xef\x86\x80"	// U+F180
#define CODICON_DEBUG_START "\xef\x86\x81"	// U+F181
#define CODICON_DEBUG_STEP_BACK "\xef\x86\x82"	// U+F182
#define CODICON_DEBUG_STEP_INTO "\xef\x86\x83"	// U+F183
#define CODICON_DEBUG_STEP_OUT "\xef\x86\x84"	// U+F184
#define CODICON_DEBUG_STEP_OVER "\xef\x86\x85"	// U+F185
#define CODICON_DEBUG_STOP "\xef\x86\x86"	// U+F186
#define CODICON_DEBUG "\xef\x86\x87"	// U+F187
#define CODICON_DESKTOP_DOWNLOAD "\xef\x86\x88"	// U+F188
#define CODICON_DEVICE_CAMERA_VIDEO "\xef\x86\x89"	// U+F189
#define CODICON_DEVICE_CAMERA "\xef\x86\x8a"	// U+F18A
#define CODICON_DEVICE_MOBILE "\xef\x86\x8b"	// U+F18B
#define CODICON_DIFF_ADDED "\xef\x86\x8c"	// U+F18C
#define CODICON_DIFF_IGNORED "\xef\x86\x8d"	// U+F18D
#define CODICON_DIFF_MODIFIED "\xef\x86\x8e"	// U+F18E
#define CODICON_DIFF_MULTIPLE "\xef\x86\x8f"	// U+F18F
#define CODICON_DIFF_REMOVED "\xef\x86\x90"	// U+F190
#define CODICON_DIFF_RENAMED "\xef\x86\x91"	// U+F191
#define CODICON_DIFF_SINGLE "\xef\x86\x92"	// U+F192
#define CODICON_DIFF "\xef\x86\x93"	// U+F193
#define CODICON_DISCARD "\xef\x86\x94"	// U+F194
#define CODICON_EDIT_SESSION "\xef\x86\x95"	// U+F195
#define CODICON_EDIT_SPARKLE "\xef\x86\x96"	// U+F196
#define CODICON_EDIT "\xef\x86\x97"	// U+F197
#define CODICON_EDITOR_LAYOUT "\xef\x86\x98"	// U+F198
#define CODICON_ELLIPSIS "\xef\x86\x99"	// U+F199
#define CODICON_EMPTY_WINDOW "\xef\x86\x9a"	// U+F19A
#define CODICON_ERROR_SMALL "\xef\x86\x9b"	// U+F19B
#define CODICON_ERROR "\xef\x86\x9c"	// U+F19C
#define CODICON_EXCLUDE "\xef\x86\x9d"	// U+F19D
#define CODICON_EXPAND_ALL "\xef\x86\x9e"	// U+F19E
#define CODICON_EXPORT "\xef\x86\x9f"	// U+F19F
#define CODICON_EXTENSIONS_LARGE "\xef\x86\xa0"	// U+F1A0
#define CODICON_EXTENSIONS "\xef\x86\xa1"	// U+F1A1
#define CODICON_EYE_CLOSED "\xef\x86\xa2"	// U+F1A2
#define CODICON_EYE "\xef\x86\xa3"	// U+F1A3
#define CODICON_FEEDBACK "\xef\x86\xa4"	// U+F1A4
#define CODICON_FILE_BINARY "\xef\x86\xa5"	// U+F1A5
#define CODICON_FILE_CODE "\xef\x86\xa6"	// U+F1A6
#define CODICON_FILE_MEDIA "\xef\x86\xa7"	// U+F1A7
#define CODICON_FILE_PDF "\xef\x86\xa8"	// U+F1A8
#define CODICON_FILE_SUBMODULE "\xef\x86\xa9"	// U+F1A9
#define CODICON_FILE_SYMLINK_DIRECTORY "\xef\x86\xaa"	// U+F1AA
#define CODICON_FILE_SYMLINK_FILE "\xef\x86\xab"	// U+F1AB
#define CODICON_FILE_ZIP "\xef\x86\xac"	// U+F1AC
#define CODICON_FILE "\xef\x86\xad"	// U+F1AD
#define CODICON_FILES "\xef\x86\xae"	// U+F1AE
#define CODICON_FILTER_FILLED "\xef\x86\xaf"	// U+F1AF
#define CODICON_FILTER "\xef\x86\xb0"	// U+F1B0
#define CODICON_FLAG "\xef\x86\xb1"	// U+F1B1
#define CODICON_FLAME "\xef\x86\xb2"	// U+F1B2
#define CODICON_FOLD_DOWN "\xef\x86\xb3"	// U+F1B3
#define CODICON_FOLD_UP "\xef\x86\xb4"	// U+F1B4
#define CODICON_FOLD "\xef\x86\xb5"	// U+F1B5
#define CODICON_FOLDER_ACTIVE "\xef\x86\xb6"	// U+F1B6
#define CODICON_FOLDER_LIBRARY "\xef\x86\xb7"	// U+F1B7
#define CODICON_FOLDER_OPENED "\xef\x86\xb8"	// U+F1B8
#define CODICON_FOLDER "\xef\x86\xb9"	// U+F1B9
#define CODICON_GAME "\xef\x86\xba"	// U+F1BA
#define CODICON_GEAR "\xef\x86\xbb"	// U+F1BB
#define CODICON_GIFT "\xef\x86\xbc"	// U+F1BC
#define CODICON_GIST_SECRET "\xef\x86\xbd"	// U+F1BD
#define CODICON_GIST "\xef\x86\xbe"	// U+F1BE
#define CODICON_GIT_COMMIT "\xef\x86\xbf"	// U+F1BF
#define CODICON_GIT_COMPARE "\xef\x87\x80"	// U+F1C0
#define CODICON_GIT_FETCH "\xef\x87\x81"	// U+F1C1
#define CODICON_GIT_MERGE "\xef\x87\x82"	// U+F1C2
#define CODICON_GIT_PULL_REQUEST_CLOSED "\xef\x87\x83"	// U+F1C3
#define CODICON_GIT_PULL_REQUEST_CREATE "\xef\x87\x84"	// U+F1C4
#define CODICON_GIT_PULL_REQUEST_DONE "\xef\x87\x85"	// U+F1C5
#define CODICON_GIT_PULL_REQUEST_DRAFT "\xef\x87\x86"	// U+F1C6
#define CODICON_GIT_PULL_REQUEST_GO_TO_CHANGES "\xef\x87\x87"	// U+F1C7
#define CODICON_GIT_PULL_REQUEST_NEW_CHANGES "\xef\x87\x88"	// U+F1C8
#define CODICON_GIT_PULL_REQUEST "\xef\x87\x89"	// U+F1C9
#define CODICON_GIT_STASH_APPLY "\xef\x87\x8a"	// U+F1CA
#define CODICON_GIT_STASH_POP "\xef\x87\x8b"	// U+F1CB
#define CODICON_GIT_STASH "\xef\x87\x8c"	// U+F1CC
#define CODICON_GITHUB_ACTION "\xef\x87\x8d"	// U+F1CD
#define CODICON_GITHUB_ALT "\xef\x87\x8e"	// U+F1CE
#define CODICON_GITHUB_INVERTED "\xef\x87\x8f"	// U+F1CF
#define CODICON_GITHUB_PROJECT "\xef\x87\x90"	// U+F1D0
#define CODICON_GITHUB "\xef\x87\x91"	// U+F1D1
#define CODICON_GLOBE "\xef\x87\x92"	// U+F1D2
#define CODICON_GO_TO_EDITING_SESSION "\xef\x87\x93"	// U+F1D3
#define CODICON_GO_TO_FILE "\xef\x87\x94"	// U+F1D4
#define CODICON_GO_TO_SEARCH "\xef\x87\x95"	// U+F1D5
#define CODICON_GRABBER "\xef\x87\x96"	// U+F1D6
#define CODICON_GRAPH_LEFT "\xef\x87\x97"	// U+F1D7
#define CODICON_GRAPH_LINE "\xef\x87\x98"	// U+F1D8
#define CODICON_GRAPH_SCATTER "\xef\x87\x99"	// U+F1D9
#define CODICON_GRAPH "\xef\x87\x9a"	// U+F1DA
#define CODICON_GRIPPER "\xef\x87\x9b"	// U+F1DB
#define CODICON_GROUP_BY_REF_TYPE "\xef\x87\x9c"	// U+F1DC
#define CODICON_HEART_FILLED "\xef\x87\x9d"	// U+F1DD
#define CODICON_HEART "\xef\x87\x9e"	// U+F1DE
#define CODICON_HISTORY "\xef\x87\x9f"	// U+F1DF
#define CODICON_HOME "\xef\x87\xa0"	// U+F1E0
#define CODICON_HORIZONTAL_RULE "\xef\x87\xa1"	// U+F1E1
#define CODICON_HUBOT "\xef\x87\xa2"	// U+F1E2
#define CODICON_INBOX "\xef\x87\xa3"	// U+F1E3
#define CODICON_INDENT "\xef\x87\xa4"	// U+F1E4
#define CODICON_INFO "\xef\x87\xa5"	// U+F1E5
#define CODICON_INSERT "\xef\x87\xa6"	// U+F1E6
#define CODICON_INSPECT "\xef\x87\xa7"	// U+F1E7
#define CODICON_ISSUE_DRAFT "\xef\x87\xa8"	// U+F1E8
#define CODICON_ISSUE_REOPENED "\xef\x87\xa9"	// U+F1E9
#define CODICON_ISSUES "\xef\x87\xaa"	// U+F1EA
#define CODICON_ITALIC "\xef\x87\xab"	// U+F1EB
#define CODICON_JERSEY "\xef\x87\xac"	// U+F1EC
#define CODICON_JSON "\xef\x87\xad"	// U+F1ED
#define CODICON_KEBAB_VERTICAL "\xef\x87\xae"	// U+F1EE
#define CODICON_KEY "\xef\x87\xaf"	// U+F1EF
#define CODICON_KEYBOARD_TAB_ABOVE "\xef\x87\xb0"	// U+F1F0
#define CODICON_KEYBOARD_TAB_BELOW "\xef\x87\xb1"	// U+F1F1
#define CODICON_KEYBOARD_TAB "\xef\x87\xb2"	// U+F1F2
#define CODICON_LAW "\xef\x87\xb3"	// U+F1F3
#define CODICON_LAYERS_ACTIVE "\xef\x87\xb4"	// U+F1F4
#define CODICON_LAYERS_DOT "\xef\x87\xb5"	// U+F1F5
#define CODICON_LAYERS "\xef\x87\xb6"	// U+F1F6
#define CODICON_LAYOUT_ACTIVITYBAR_LEFT "\xef\x87\xb7"	// U+F1F7
#define CODICON_LAYOUT_ACTIVITYBAR_RIGHT "\xef\x87\xb8"	// U+F1F8
#define CODICON_LAYOUT_CENTERED "\xef\x87\xb9"	// U+F1F9
#define CODICON_LAYOUT_MENUBAR "\xef\x87\xba"	// U+F1FA
#define CODICON_LAYOUT_PANEL_CENTER "\xef\x87\xbb"	// U+F1FB
#define CODICON_LAYOUT_PANEL_DOCK "\xef\x87\xbc"	// U+F1FC
#define CODICON_LAYOUT_PANEL_JUSTIFY "\xef\x87\xbd"	// U+F1FD
#define CODICON_LAYOUT_PANEL_LEFT "\xef\x87\xbe"	// U+F1FE
#define CODICON_LAYOUT_PANEL_OFF "\xef\x87\xbf"	// U+F1FF
#define CODICON_LAYOUT_PANEL_RIGHT "\xef\x88\x80"	// U+F200
#define CODICON_LAYOUT_PANEL "\xef\x88\x81"	// U+F201
#define CODICON_LAYOUT_SIDEBAR_LEFT_DOCK "\xef\x88\x82"	// U+F202
#define CODICON_LAYOUT_SIDEBAR_LEFT_OFF "\xef\x88\x83"	// U+F203
#define CODICON_LAYOUT_SIDEBAR_LEFT "\xef\x88\x84"	// U+F204
#define CODICON_LAYOUT_SIDEBAR_RIGHT_DOCK "\xef\x88\x85"	// U+F205
#define CODICON_LAYOUT_SIDEBAR_RIGHT_OFF "\xef\x88\x86"	// U+F206
#define CODICON_LAYOUT_SIDEBAR_RIGHT "\xef\x88\x87"	// U+F207
#define CODICON_LAYOUT_STATUSBAR "\xef\x88\x88"	// U+F208
#define CODICON_LAYOUT "\xef\x88\x89"	// U+F209
#define CODICON_LIBRARY "\xef\x88\x8a"	// U+F20A
#define CODICON_LIGHTBULB_AUTOFIX "\xef\x88\x8b"	// U+F20B
#define CODICON_LIGHTBULB_EMPTY "\xef\x88\x8c"	// U+F20C
#define CODICON_LIGHTBULB_SPARKLE "\xef\x88\x8d"	// U+F20D
#define CODICON_LIGHTBULB "\xef\x88\x8e"	// U+F20E
#define CODICON_LINK_EXTERNAL "\xef\x88\x8f"	// U+F20F
#define CODICON_LINK "\xef\x88\x90"	// U+F210
#define CODICON_LIST_FILTER "\xef\x88\x91"	// U+F211
#define CODICON_LIST_FLAT "\xef\x88\x92"	// U+F212
#define CODICON_LIST_ORDERED "\xef\x88\x93"	// U+F213
#define CODICON_LIST_SELECTION "\xef\x88\x94"	// U+F214
#define CODICON_LIST_TREE "\xef\x88\x95"	// U+F215
#define CODICON_LIST_UNORDERED "\xef\x88\x96"	// U+F216
#define CODICON_LIVE_SHARE "\xef\x88\x97"	// U+F217
#define CODICON_LOADING "\xef\x88\x98"	// U+F218
#define CODICON_LOCATION "\xef\x88\x99"	// U+F219
#define CODICON_LOCK_SMALL "\xef\x88\x9a"	// U+F21A
#define CODICON_LOCK "\xef\x88\x9b"	// U+F21B
#define CODICON_MAGNET "\xef\x88\x9c"	// U+F21C
#define CODICON_MAIL_READ "\xef\x88\x9d"	// U+F21D
#define CODICON_MAIL "\xef\x88\x9e"	// U+F21E
#define CODICON_MAP_FILLED "\xef\x88\x9f"	// U+F21F
#define CODICON_MAP_VERTICAL_FILLED "\xef\x88\xa0"	// U+F220
#define CODICON_MAP_VERTICAL "\xef\x88\xa1"	// U+F221
#define CODICON_MAP "\xef\x88\xa2"	// U+F222
#define CODICON_MARKDOWN "\xef\x88\xa3"	// U+F223
#define CODICON_MCP "\xef\x88\xa4"	// U+F224
#define CODICON_MEGAPHONE "\xef\x88\xa5"	// U+F225
#define CODICON_MENTION "\xef\x88\xa6"	// U+F226
#define CODICON_MENU "\xef\x88\xa7"	// U+F227
#define CODICON_MERGE "\xef\x88\xa8"	// U+F228
#define CODICON_MIC_FILLED "\xef\x88\xa9"	// U+F229
#define CODICON_MIC "\xef\x88\xaa"	// U+F22A
#define CODICON_MILESTONE "\xef\x88\xab"	// U+F22B
#define CODICON_MIRROR "\xef\x88\xac"	// U+F22C
#define CODICON_MORTAR_BOARD "\xef\x88\xad"	// U+F22D
#define CODICON_MOVE "\xef\x88\xae"	// U+F22E
#define CODICON_MULTIPLE_WINDOWS "\xef\x88\xaf"	// U+F22F
#define CODICON_MUSIC "\xef\x88\xb0"	// U+F230
#define CODICON_MUTE "\xef\x88\xb1"	// U+F231
#define CODICON_NEW_FILE "\xef\x88\xb2"	// U+F232
#define CODICON_NEW_FOLDER "\xef\x88\xb3"	// U+F233
#define CODICON_NEWLINE "\xef\x88\xb4"	// U+F234
#define CODICON_NO_NEWLINE "\xef\x88\xb5"	// U+F235
#define CODICON_NOTE "\xef\x88\xb6"	// U+F236
#define CODICON_NOTEBOOK_TEMPLATE "\xef\x88\xb7"	// U+F237
#define CODICON_NOTEBOOK "\xef\x88\xb8"	// U+F238
#define CODICON_OCTOFACE "\xef\x88\xb9"	// U+F239
#define CODICON_OPEN_PREVIEW "\xef\x88\xba"	// U+F23A
#define CODICON_ORGANIZATION "\xef\x88\xbb"	// U+F23B
#define CODICON_OUTPUT "\xef\x88\xbc"	// U+F23C
#define CODICON_PACKAGE "\xef\x88\xbd"	// U+F23D
#define CODICON_PAINTCAN "\xef\x88\xbe"	// U+F23E
#define CODICON_PASS_FILLED "\xef\x88\xbf"	// U+F23F
#define CODICON_PASS "\xef\x89\x80"	// U+F240
#define CODICON_PERCENTAGE "\xef\x89\x81"	// U+F241
#define CODICON_PERSON_ADD "\xef\x89\x82"	// U+F242
#define CODICON_PERSON "\xef\x89\x83"	// U+F243
#define CODICON_PIANO "\xef\x89\x84"	// U+F244
#define CODICON_PIE_CHART "\xef\x89\x85"	// U+F245
#define CODICON_PIN "\xef\x89\x86"	// U+F246
#define CODICON_PINNED_DIRTY "\xef\x89\x87"	// U+F247
#define CODICON_PINNED "\xef\x89\x88"	// U+F248
#define CODICON_PLAY_CIRCLE "\xef\x89\x89"	// U+F249
#define CODICON_PLAY "\xef\x89\x8a"	// U+F24A
#define CODICON_PLUG "\xef\x89\x8b"	// U+F24B
#define CODICON_PRESERVE_CASE "\xef\x89\x8c"	// U+F24C
#define CODICON_PREVIEW "\xef\x89\x8d"	// U+F24D
#define CODICON_PRIMITIVE_SQUARE "\xef\x89\x8e"	// U+F24E
#define CODICON_PROJECT "\xef\x89\x8f"	// U+F24F
#define CODICON_PULSE "\xef\x89\x90"	// U+F250
#define CODICON_PYTHON "\xef\x89\x91"	// U+F251
#define CODICON_QUESTION "\xef\x89\x92"	// U+F252
#define CODICON_QUOTE "\xef\x89\x93"	// U+F253
#define CODICON_RADIO_TOWER "\xef\x89\x94"	// U+F254
#define CODICON_REACTIONS "\xef\x89\x95"	// U+F255
#define CODICON_RECORD_KEYS "\xef\x89\x96"	// U+F256
#define CODICON_RECORD_SMALL "\xef\x89\x97"	// U+F257
#define CODICON_RECORD "\xef\x89\x98"	// U+F258
#define CODICON_REDO "\xef\x89\x99"	// U+F259
#define CODICON_REFERENCES "\xef\x89\x9a"	// U+F25A
#define CODICON_REFRESH "\xef\x89\x9b"	// U+F25B
#define CODICON_REGEX "\xef\x89\x9c"	// U+F25C
#define CODICON_REMOTE_EXPLORER "\xef\x89\x9d"	// U+F25D
#define CODICON_REMOTE "\xef\x89\x9e"	// U+F25E
#define CODICON_REMOVE "\xef\x89\x9f"	// U+F25F
#define CODICON_REPLACE_ALL "\xef\x89\xa0"	// U+F260
#define CODICON_REPLACE "\xef\x89\xa1"	// U+F261
#define CODICON_REPLY "\xef\x89\xa2"	// U+F262
#define CODICON_REPO_CLONE "\xef\x89\xa3"	// U+F263
#define CODICON_REPO_FETCH "\xef\x89\xa4"	// U+F264
#define CODICON_REPO_FORCE_PUSH "\xef\x89\xa5"	// U+F265
#define CODICON_REPO_FORKED "\xef\x89\xa6"	// U+F266
#define CODICON_REPO_PINNED "\xef\x89\xa7"	// U+F267
#define CODICON_REPO_PULL "\xef\x89\xa8"	// U+F268
#define CODICON_REPO_PUSH "\xef\x89\xa9"	// U+F269
#define CODICON_REPO "\xef\x89\xaa"	// U+F26A
#define CODICON_REPORT "\xef\x89\xab"	// U+F26B
#define CODICON_REQUEST_CHANGES "\xef\x89\xac"	// U+F26C
#define CODICON_ROBOT "\xef\x89\xad"	// U+F26D
#define CODICON_ROCKET "\xef\x89\xae"	// U+F26E
#define CODICON_ROOT_FOLDER_OPENED "\xef\x89\xaf"	// U+F26F
#define CODICON_ROOT_FOLDER "\xef\x89\xb0"	// U+F270
#define CODICON_RSS "\xef\x89\xb1"	// U+F271
#define CODICON_RUBY "\xef\x89\xb2"	// U+F272
#define CODICON_RUN_ABOVE "\xef\x89\xb3"	// U+F273
#define CODICON_RUN_ALL_COVERAGE "\xef\x89\xb4"	// U+F274
#define CODICON_RUN_ALL "\xef\x89\xb5"	// U+F275
#define CODICON_RUN_BELOW "\xef\x89\xb6"	// U+F276
#define CODICON_RUN_COVERAGE "\xef\x89\xb7"	// U+F277
#define CODICON_RUN_ERRORS "\xef\x89\xb8"	// U+F278
#define CODICON_SAVE_ALL "\xef\x89\xb9"	// U+F279
#define CODICON_SAVE_AS "\xef\x89\xba"	// U+F27A
#define CODICON_SAVE "\xef\x89\xbb"	// U+F27B
#define CODICON_SCREEN_FULL "\xef\x89\xbc"	// U+F27C
#define CODICON_SCREEN_NORMAL "\xef\x89\xbd"	// U+F27D
#define CODICON_SEARCH_FUZZY "\xef\x89\xbe"	// U+F27E
#define CODICON_SEARCH_SPARKLE "\xef\x89\xbf"	// U+F27F
#define CODICON_SEARCH_STOP "\xef\x8a\x80"	// U+F280
#define CODICON_SEARCH "\xef\x8a\x81"	// U+F281
#define CODICON_SEND_TO_REMOTE_AGENT "\xef\x8a\x82"	// U+F282
#define CODICON_SEND "\xef\x8a\x83"	// U+F283
#define CODICON_SERVER_ENVIRONMENT "\xef\x8a\x84"	// U+F284
#define CODICON_SERVER_PROCESS "\xef\x8a\x85"	// U+F285
#define CODICON_SERVER "\xef\x8a\x86"	// U+F286
#define CODICON_SETTINGS_GEAR "\xef\x8a\x87"	// U+F287
#define CODICON_SETTINGS "\xef\x8a\x88"	// U+F288
#define CODICON_SHARE "\xef\x8a\x89"	// U+F289
#define CODICON_SHIELD "\xef\x8a\x8a"	// U+F28A
#define CODICON_SIGN_IN "\xef\x8a\x8b"	// U+F28B
#define CODICON_SIGN_OUT "\xef\x8a\x8c"	// U+F28C
#define CODICON_SMILEY "\xef\x8a\x8d"	// U+F28D
#define CODICON_SNAKE "\xef\x8a\x8e"	// U+F28E
#define CODICON_SORT_PRECEDENCE "\xef\x8a\x8f"	// U+F28F
#define CODICON_SOURCE_CONTROL "\xef\x8a\x90"	// U+F290
#define CODICON_SPARKLE_FILLED "\xef\x8a\x91"	// U+F291
#define CODICON_SPARKLE "\xef\x8a\x92"	// U+F292
#define CODICON_SPLIT_HORIZONTAL "\xef\x8a\x93"	// U+F293
#define CODICON_SPLIT_VERTICAL "\xef\x8a\x94"	// U+F294
#define CODICON_SQUIRREL "\xef\x8a\x95"	// U+F295
#define CODICON_STAR_EMPTY "\xef\x8a\x96"	// U+F296
#define CODICON_STAR_FULL "\xef\x8a\x97"	// U+F297
#define CODICON_STAR_HALF "\xef\x8a\x98"	// U+F298
#define CODICON_STOP_CIRCLE "\xef\x8a\x99"	// U+F299
#define CODICON_SURROUND_WITH "\xef\x8a\x9a"	// U+F29A
#define CODICON_SYMBOL_ARRAY "\xef\x8a\x9b"	// U+F29B
#define CODICON_SYMBOL_BOOLEAN "\xef\x8a\x9c"	// U+F29C
#define CODICON_SYMBOL_CLASS "\xef\x8a\x9d"	// U+F29D
#define CODICON_SYMBOL_COLOR "\xef\x8a\x9e"	// U+F29E
#define CODICON_SYMBOL_CONSTANT "\xef\x8a\x9f"	// U+F29F
#define CODICON_SYMBOL_ENUM_MEMBER "\xef\x8a\xa0"	// U+F2A0
#define CODICON_SYMBOL_ENUM "\xef\x8a\xa1"	// U+F2A1
#define CODICON_SYMBOL_EVENT "\xef\x8a\xa2"	// U+F2A2
#define CODICON_SYMBOL_FIELD "\xef\x8a\xa3"	// U+F2A3
#define CODICON_SYMBOL_FILE "\xef\x8a\xa4"	// U+F2A4
#define CODICON_SYMBOL_INTERFACE "\xef\x8a\xa5"	// U+F2A5
#define CODICON_SYMBOL_KEY "\xef\x8a\xa6"	// U+F2A6
#define CODICON_SYMBOL_KEYWORD "\xef\x8a\xa7"	// U+F2A7
#define CODICON_SYMBOL_METHOD_ARROW "\xef\x8a\xa8"	// U+F2A8
#define CODICON_SYMBOL_METHOD "\xef\x8a\xa9"	// U+F2A9
#define CODICON_SYMBOL_MISC "\xef\x8a\xaa"	// U+F2AA
#define CODICON_SYMBOL_NAMESPACE "\xef\x8a\xab"	// U+F2AB
#define CODICON_SYMBOL_NUMERIC "\xef\x8a\xac"	// U+F2AC
#define CODICON_SYMBOL_OPERATOR "\xef\x8a\xad"	// U+F2AD
#define CODICON_SYMBOL_PARAMETER "\xef\x8a\xae"	// U+F2AE
#define CODICON_SYMBOL_PROPERTY "\xef\x8a\xaf"	// U+F2AF
#define CODICON_SYMBOL_RULER "\xef\x8a\xb0"	// U+F2B0
#define CODICON_SYMBOL_SNIPPET "\xef\x8a\xb1"	// U+F2B1
#define CODICON_SYMBOL_STRING "\xef\x8a\xb2"	// U+F2B2
#define CODICON_SYMBOL_STRUCTURE "\xef\x8a\xb3"	// U+F2B3
#define CODICON_SYMBOL_VARIABLE "\xef\x8a\xb4"	// U+F2B4
#define CODICON_SYNC_IGNORED "\xef\x8a\xb5"	// U+F2B5
#define CODICON_SYNC "\xef\x8a\xb6"	// U+F2B6
#define CODICON_TABLE "\xef\x8a\xb7"	// U+F2B7
#define CODICON_TAG "\xef\x8a\xb8"	// U+F2B8
#define CODICON_TARGET "\xef\x8a\xb9"	// U+F2B9
#define CODICON_TASKLIST "\xef\x8a\xba"	// U+F2BA
#define CODICON_TELESCOPE "\xef\x8a\xbb"	// U+F2BB
#define CODICON_TERMINAL_BASH "\xef\x8a\xbc"	// U+F2BC
#define CODICON_TERMINAL_CMD "\xef\x8a\xbd"	// U+F2BD
#define CODICON_TERMINAL_DEBIAN "\xef\x8a\xbe"	// U+F2BE
#define CODICON_TERMINAL_LINUX "\xef\x8a\xbf"	// U+F2BF
#define CODICON_TERMINAL_POWERSHELL "\xef\x8b\x80"	// U+F2C0
#define CODICON_TERMINAL_TMUX "\xef\x8b\x81"	// U+F2C1
#define CODICON_TERMINAL_UBUNTU "\xef\x8b\x82"	// U+F2C2
#define CODICON_TERMINAL "\xef\x8b\x83"	// U+F2C3
#define CODICON_TEXT_SIZE "\xef\x8b\x84"	// U+F2C4
#define CODICON_THREE_BARS "\xef\x8b\x85"	// U+F2C5
#define CODICON_THUMBSDOWN_FILLED "\xef\x8b\x86"	// U+F2C6
#define CODICON_THUMBSDOWN "\xef\x8b\x87"	// U+F2C7
#define CODICON_THUMBSUP_FILLED "\xef\x8b\x88"	// U+F2C8
#define CODICON_THUMBSUP "\xef\x8b\x89"	// U+F2C9
#define CODICON_TOOLS "\xef\x8b\x8a"	// U+F2CA
#define CODICON_TRASH "\xef\x8b\x8b"	// U+F2CB
#define CODICON_TRIANGLE_DOWN "\xef\x8b\x8c"	// U+F2CC
#define CODICON_TRIANGLE_LEFT "\xef\x8b\x8d"	// U+F2CD
#define CODICON_TRIANGLE_RIGHT "\xef\x8b\x8e"	// U+F2CE
#define CODICON_TRIANGLE_UP "\xef\x8b\x8f"	// U+F2CF
#define CODICON_TWITTER "\xef\x8b\x90"	// U+F2D0
#define CODICON_TYPE_HIERARCHY_SUB "\xef\x8b\x91"	// U+F2D1
#define CODICON_TYPE_HIERARCHY_SUPER "\xef\x8b\x92"	// U+F2D2
#define CODICON_TYPE_HIERARCHY "\xef\x8b\x93"	// U+F2D3
#define CODICON_UNFOLD "\xef\x8b\x94"	// U+F2D4
#define CODICON_UNGROUP_BY_REF_TYPE "\xef\x8b\x95"	// U+F2D5
#define CODICON_UNLOCK "\xef\x8b\x96"	// U+F2D6
#define CODICON_UNMUTE "\xef\x8b\x97"	// U+F2D7
#define CODICON_UNVERIFIED "\xef\x8b\x98"	// U+F2D8
#define CODICON_VARIABLE_GROUP "\xef\x8b\x99"	// U+F2D9
#define CODICON_VERIFIED_FILLED "\xef\x8b\x9a"	// U+F2DA
#define CODICON_VERIFIED "\xef\x8b\x9b"	// U+F2DB
#define CODICON_VERSIONS "\xef\x8b\x9c"	// U+F2DC
#define CODICON_VM_ACTIVE "\xef\x8b\x9d"	// U+F2DD
#define CODICON_VM_CONNECT "\xef\x8b\x9e"	// U+F2DE
#define CODICON_VM_OUTLINE "\xef\x8b\x9f"	// U+F2DF
#define CODICON_VM_RUNNING "\xef\x8b\xa0"	// U+F2E0
#define CODICON_VM "\xef\x8b\xa1"	// U+F2E1
#define CODICON_VR "\xef\x8b\xa2"	// U+F2E2
#define CODICON_VSCODE_INSIDERS "\xef\x8b\xa3"	// U+F2E3
#define CODICON_VSCODE "\xef\x8b\xa4"	// U+F2E4
#define CODICON_WAND "\xef\x8b\xa5"	// U+F2E5
#define CODICON_WARNING "\xef\x8b\xa6"	// U+F2E6
#define CODICON_WATCH "\xef\x8b\xa7"	// U+F2E7
#define CODICON_WHITESPACE "\xef\x8b\xa8"	// U+F2E8
#define CODICON_WHOLE_WORD "\xef\x8b\xa9"	// U+F2E9
#define CODICON_WINDOW "\xef\x8b\xaa"	// U+F2EA
#define CODICON_WORD_WRAP "\xef\x8b\xab"	// U+F2EB
#define CODICON_WORKSPACE_TRUSTED "\xef\x8b\xac"	// U+F2EC
#define CODICON_WORKSPACE_UNKNOWN "\xef\x8b\xad"	// U+F2ED
#define CODICON_WORKSPACE_UNTRUSTED "\xef\x8b\xae"	// U+F2EE
#define CODICON_ZOOM_IN "\xef\x8b\xaf"	// U+F2EF
#define CODICON_ZOOM_OUT "\xef\x8b\xb0"	// U+F2F0
